from enum import Enum


class UserRole(str, Enum):
    SUPERADMIN = "SUPERADMIN"
    ADMIN = "ADMIN"
    ANALYST = "ANALYST"
    VIEWER = "VIEWER"


class UserStatus(str, Enum):
    ACTIVE = "ACTIVE"
    BLOCKED = "BLOCKED"


class AnalysisRunStatus(str, Enum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    COMPLETED_WITH_SKIPS = "COMPLETED_WITH_SKIPS"
    FAILED = "FAILED"


class DetectedPostStatus(str, Enum):
    COUNTED = "COUNTED"
    SKIPPED_UNAVAILABLE = "SKIPPED_UNAVAILABLE"
    SKIPPED_DUPLICATE = "SKIPPED_DUPLICATE"
    SKIPPED_NO_VIEWS = "SKIPPED_NO_VIEWS"
    SKIPPED_LOW_SIMILARITY = "SKIPPED_LOW_SIMILARITY"
    SKIPPED_UNCONFIRMED = "SKIPPED_UNCONFIRMED"
    ERROR = "ERROR"


class ConfirmationType(str, Enum):
    FORWARD_CONFIRMED = "FORWARD_CONFIRMED"
    SOURCE_LINK_CONFIRMED = "SOURCE_LINK_CONFIRMED"
    FULL_TEXT_COPY_CONFIRMED = "FULL_TEXT_COPY_CONFIRMED"
    NEAR_FULL_TEXT_COPY_CONFIRMED = "NEAR_FULL_TEXT_COPY_CONFIRMED"


class AuditActionType(str, Enum):
    USER_CREATED = "USER_CREATED"
    USER_BLOCKED = "USER_BLOCKED"
    USER_UNBLOCKED = "USER_UNBLOCKED"
    USER_ROLE_CHANGED = "USER_ROLE_CHANGED"
    ANALYSIS_STARTED = "ANALYSIS_STARTED"
    ANALYSIS_COMPLETED = "ANALYSIS_COMPLETED"
    SETTING_CHANGED = "SETTING_CHANGED"
    POST_SELECTED = "POST_SELECTED"
